version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=master
      - POSTGRES_INITDB_ARGS="--auth-host=scram-sha-256"
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    networks:
      - psql
    ports:
      - "5433:5432"

volumes:
  postgres:

networks:
  psql:
    driver: bridge
