# syntax=docker/dockerfile:1


FROM golang:1.17-alpine

WORKDIR $GOPATH/src/github.com/andrewgray11/msds432finalproject
COPY ..

# Download necessary Go modules
RUN go mod download
RUN go build -0 app .

# Expose the port that the program listens on
EXPOSE 8080

# Set the command to run the program when the container starts
CMD ["chicagobi-app"]